// Generated by tools/helpertable.ts from runtime/cpm22: do not edit.
// Run `deno task helpers` after changing a helper.

/** The helper-table version the compiler is built for. */
export const HELPER_VERSION = 1;

/** The interface key of each version, 1 up to HELPER_VERSION. */
export const HELPER_KEYS: readonly number[] = [0x5524];

export type HelperFigures = {
  ordinal: number;
  name: string;
  /** 1: a service called with arguments on the stack; 2: a register helper. */
  convention: number;
  since: number;
  /** Stack bytes a returning call uses, its return address included. */
  stack: number;
  /** Stack bytes any path uses, one that ends the program included. */
  endingStack: number;
};

/** [ordinal, name, convention, since, stack, ending stack] */
const ROWS: [number, string, number, number, number, number][] = [
  [0x007, "CON_OUT", 2, 1, 6, 6],
  [0x008, "TRAP_BND", 2, 1, 2, 20],
  [0x009, "RETN", 2, 1, 2, 2],
  [0x00a, "STK_CHK", 2, 1, 2, 20],
  [0x00b, "TRAP_NAR", 2, 1, 2, 20],
  [0x00c, "TRAP_DIV", 2, 1, 2, 20],
  [0x00d, "TRAP_FOV", 2, 1, 2, 20],
  [0x00e, "TRAP_FIN", 2, 1, 2, 20],
  [0x00f, "TRAP_LOO", 2, 1, 2, 20],
  [0x010, "TRAP_ACT", 2, 1, 2, 20],
  [0x011, "TRAP_STA", 2, 1, 2, 20],
  [0x012, "TRAP_CYC", 2, 1, 2, 20],
  [0x013, "TRAP_POO", 2, 1, 2, 20],
  [0x014, "TRAP_AST", 2, 1, 2, 20],
  [0x015, "PUT_DEC", 2, 1, 10, 10],
  [0x016, "MUL16", 2, 1, 2, 2],
  [0x017, "DIV16", 2, 1, 2, 20],
  [0x018, "DIV16S", 2, 1, 8, 26],
  [0x019, "STR_SETL", 2, 1, 4, 20],
  [0x01b, "POOL_TRY", 2, 1, 8, 8],
  [0x01c, "POOL_DEL", 2, 1, 14, 14],
  [0x01d, "OBJ_FREE", 2, 1, 24, 24],
  [0x01e, "ID_CHK", 2, 1, 4, 20],
  [0x01f, "ID_TEST", 2, 1, 4, 4],
  [0x020, "WR_TEXT", 1, 1, 24, 24],
  [0x021, "WR_BYTE", 1, 1, 20, 20],
  [0x022, "WR_OUT", 1, 1, 10, 10],
  [0x023, "OWN_SET", 2, 1, 22, 22],
  [0x024, "OWN_SETC", 2, 1, 22, 22],
  [0x025, "LINK0", 2, 1, 4, 4],
  [0x026, "ID_MAKE", 2, 1, 4, 4],
  [0x028, "ADD32", 2, 1, 6, 6],
  [0x029, "SUB32", 2, 1, 6, 6],
  [0x02a, "CMP32U", 2, 1, 6, 6],
  [0x02b, "CMP32S", 2, 1, 6, 6],
  [0x02c, "NEG32", 2, 1, 2, 2],
  [0x02d, "MUL32", 2, 1, 4, 4],
  [0x02e, "DIV32U", 2, 1, 6, 20],
  [0x02f, "DIV32S", 2, 1, 12, 26],
  [0x030, "AND32", 2, 1, 6, 6],
  [0x031, "OR32", 2, 1, 6, 6],
  [0x032, "XOR32", 2, 1, 6, 6],
  [0x033, "SHL32", 2, 1, 2, 2],
  [0x034, "SHR32U", 2, 1, 2, 2],
  [0x035, "SHR32S", 2, 1, 2, 2],
  [0x037, "FP_UNPK", 2, 1, 12, 12],
  [0x038, "FP_SHR", 2, 1, 2, 2],
  [0x039, "FP_PACK", 2, 1, 2, 2],
  [0x03a, "FADD", 2, 1, 14, 20],
  [0x03b, "FSUB", 2, 1, 14, 20],
  [0x03c, "FMUL", 2, 1, 14, 20],
  [0x03d, "FDIV", 2, 1, 14, 20],
  [0x03e, "FCMP", 2, 1, 8, 8],
  [0x03f, "I2F", 2, 1, 4, 4],
  [0x040, "U2F", 2, 1, 2, 2],
  [0x041, "F2I", 2, 1, 6, 20],
  [0x042, "F2U", 2, 1, 4, 20],
  [0x043, "FP_INT", 2, 1, 2, 2],
  [0x044, "FP_MAG", 2, 1, 2, 2],
  [0x06d, "RD_BYTE", 1, 1, 16, 16],
  [0x06e, "RD_IN", 1, 1, 10, 10],
  [0x06f, "RD_KEY", 1, 1, 4, 4],
  [0x070, "KEY_RDY", 1, 1, 4, 4],
  [0x071, "RD_LINE", 1, 1, 16, 16],
  [0x072, "OP_READ", 1, 1, 14, 14],
  [0x073, "OP_WRITE", 1, 1, 14, 14],
  [0x074, "OP_APPND", 1, 1, 14, 14],
  [0x075, "OP_UPDT", 1, 1, 14, 14],
  [0x076, "FS_CLOSE", 1, 1, 18, 18],
  [0x077, "FS_ABORT", 1, 1, 14, 14],
  [0x078, "FS_FLUSH", 1, 1, 12, 12],
  [0x079, "RD_BLOCK", 1, 1, 18, 18],
  [0x07a, "WR_BLOCK", 1, 1, 22, 22],
  [0x07b, "FS_SEEK", 1, 1, 12, 12],
  [0x07c, "FS_POS", 1, 1, 8, 8],
  [0x07d, "FS_SIZE", 1, 1, 12, 12],
  [0x07e, "FS_EXIST", 1, 1, 14, 14],
  [0x07f, "FS_DEL", 1, 1, 14, 14],
  [0x080, "FS_REN", 1, 1, 14, 14],
  [0x081, "FS_FIND1", 1, 1, 14, 14],
  [0x082, "FS_FINDN", 1, 1, 12, 12],
  [0x084, "CMD_TAIL", 1, 1, 6, 6],
  [0x085, "M_RESET", 1, 1, 6, 6],
  [0x086, "M_RESETD", 1, 1, 8, 8],
  [0x087, "M_DRIVE", 1, 1, 2, 2],
  [0x088, "M_SELECT", 1, 1, 8, 8],
  [0x089, "M_USER", 1, 1, 2, 2],
  [0x08a, "M_SETU", 1, 1, 6, 6],
  [0x08b, "M_RODRV", 1, 1, 6, 6],
  [0x08c, "M_FREE", 1, 1, 2, 2],
];

export const HELPER_TABLE: readonly HelperFigures[] = ROWS.map((
  [ordinal, name, convention, since, stack, endingStack],
) => ({ ordinal, name, convention, since, stack, endingStack }));
