/**
 * Generate the helper table (object format §10) from the runtime source: the
 * module the compiler carries, `ref/compile/helper-table.ts`, and the
 * published table in docs/helper-table.md. Each helper's ordinal, calling
 * convention and version come from its `@blob` line; its size from the built
 * library; its stack figures from the static analysis (tools/stack.ts).
 *
 * Usage: deno task helpers
 */
import { buildLibrary, type BuiltLibrary } from "./brl.ts";

const BEGIN = "<!-- generated by tools/helpertable.ts: begin -->";
const END = "<!-- generated by tools/helpertable.ts: end -->";
const ROOT = new URL("../", import.meta.url).pathname;
export const MODULE = `${ROOT}ref/compile/helper-table.ts`;
export const DOC = `${ROOT}docs/helper-table.md`;

const hex = (n: number, width: number) =>
  "$" + n.toString(16).toUpperCase().padStart(width, "0");

/** Build the CPM22 runtime library as the compiler's table describes it. */
export async function buildRuntime(): Promise<BuiltLibrary> {
  const source = await Deno.readTextFile(`${ROOT}runtime/cpm22/cpm22.asm`);
  return await buildLibrary(
    source,
    `${ROOT}build/helper-table`,
    `${ROOT}runtime/cpm22`,
  );
}

/** The source of ref/compile/helper-table.ts. */
export function helperModule(built: BuiltLibrary): string {
  const rows = built.helpers.map((h) =>
    `  [${
      hex(h.ordinal, 3).replace("$", "0x").toLowerCase()
    }, "${h.name}", ${h.convention}, ${h.since}, ${h.returning}, ${h.ending}],`
  );
  return [
    "// Generated by tools/helpertable.ts from runtime/cpm22: do not edit.",
    "// Run `deno task helpers` after changing a helper.",
    "",
    "/** The helper-table version the compiler is built for. */",
    `export const HELPER_VERSION = ${built.helperVersion};`,
    "",
    "/** The interface key of each version, 1 up to HELPER_VERSION. */",
    `export const HELPER_KEYS: readonly number[] = [${
      built.helperKeys.map((k) => hex(k, 4).replace("$", "0x").toLowerCase())
        .join(", ")
    }];`,
    "",
    "export type HelperFigures = {",
    "  ordinal: number;",
    "  name: string;",
    "  /** 1: a service called with arguments on the stack; 2: a register helper. */",
    "  convention: number;",
    "  since: number;",
    "  /** Stack bytes a returning call uses, its return address included. */",
    "  stack: number;",
    "  /** Stack bytes any path uses, one that ends the program included. */",
    "  endingStack: number;",
    "};",
    "",
    "/** [ordinal, name, convention, since, stack, ending stack] */",
    "const ROWS: [number, string, number, number, number, number][] = [",
    ...rows,
    "];",
    "",
    "export const HELPER_TABLE: readonly HelperFigures[] = ROWS.map((",
    "  [ordinal, name, convention, since, stack, endingStack],",
    ") => ({ ordinal, name, convention, since, stack, endingStack }));",
    "",
  ].join("\n");
}

/** The generated section of docs/helper-table.md. */
export function helperTables(
  built: BuiltLibrary,
  basieNames: Map<number, string>,
): string {
  const out = [
    BEGIN,
    "",
    `Helper-table version ${built.helperVersion}; interface keys ${
      built.helperKeys.map((k, i) => `v${i + 1} ${hex(k, 4)}`).join(", ")
    }.`,
    "",
    "| Ordinal | Blob | Called as | Since | Bytes | Stack | Ending stack |",
    "| ---: | --- | --- | ---: | ---: | ---: | ---: |",
  ];
  let bytes = 0;
  for (const h of built.helpers) {
    const as = basieNames.get(h.ordinal);
    const called = as
      ? `\`${as}\``
      : h.convention === 1
      ? "service"
      : "register helper";
    out.push(
      `| ${
        hex(h.ordinal, 3)
      } | \`${h.name}\` | ${called} | ${h.since} | ${h.size} | ${h.returning} | ${h.ending} |`,
    );
    bytes += h.size;
  }
  out.push(
    "",
    `${built.helpers.length} helpers, ${bytes} bytes; the largest ending stack is ${
      Math.max(...built.helpers.map((h) => h.ending))
    } bytes.`,
    "",
    END,
  );
  return out.join("\n");
}

/** docs/helper-table.md with its generated section replaced. */
export function updateDoc(doc: string, section: string): string {
  const i = doc.indexOf(BEGIN);
  const j = doc.indexOf(END);
  if (i < 0 || j < 0) {
    throw new Error("helper-table.md has no generated section");
  }
  return doc.slice(0, i) + section + doc.slice(j + END.length);
}

/** Basie names of the services, by ordinal. */
export async function serviceNames(): Promise<Map<number, string>> {
  const { SERVICES } = await import("../ref/compile/helpers.ts");
  return new Map(SERVICES.map((s) => [s.ordinal, s.name]));
}

if (import.meta.main) {
  const built = await buildRuntime();
  await Deno.writeTextFile(MODULE, helperModule(built));
  const doc = await Deno.readTextFile(DOC);
  await Deno.writeTextFile(
    DOC,
    updateDoc(doc, helperTables(built, await serviceNames())),
  );
  console.log(
    `${built.helpers.length} helpers; ref/compile/helper-table.ts and docs/helper-table.md updated`,
  );
}
