/**
 * Generate BASIE.MSG and the code tables of docs/diagnostics.md from the
 * message table (ref/compile/messages.ts), the single source of both.
 *
 * Usage: deno run --allow-read --allow-write tools/msgfile.ts [OUT.MSG]
 */
import { type Group, messageFile, MESSAGES } from "../ref/compile/messages.ts";

const BEGIN = "<!-- generated by tools/msgfile.ts: begin -->";
const END = "<!-- generated by tools/msgfile.ts: end -->";

/** The register's code tables, grouped, in number order. */
export function registerTables(): string {
  const groups = new Map<Group, typeof MESSAGES>();
  for (const m of [...MESSAGES].sort((a, b) => a.number - b.number)) {
    if (!groups.has(m.group)) groups.set(m.group, []);
    groups.get(m.group)!.push(m);
  }
  const out: string[] = [BEGIN, ""];
  for (const [group, list] of groups) {
    out.push(
      `## ${group}`,
      "",
      "| Number | Code | Message |",
      "| ---: | --- | --- |",
    );
    for (const m of list) {
      out.push(`| ${m.number} | \`${m.code}\` | ${m.text} |`);
    }
    out.push("");
  }
  out.push(END);
  return out.join("\n");
}

/** docs/diagnostics.md with its generated section replaced. */
export function updateRegister(doc: string): string {
  const i = doc.indexOf(BEGIN);
  const j = doc.indexOf(END);
  if (i < 0 || j < 0) {
    throw new Error("diagnostics.md has no generated section");
  }
  return doc.slice(0, i) + registerTables() + doc.slice(j + END.length);
}

if (import.meta.main) {
  const out = Deno.args[0] ?? "build/BASIE.MSG";
  const file = messageFile();
  await Deno.writeFile(out, file);
  const path = new URL("../docs/diagnostics.md", import.meta.url).pathname;
  const doc = await Deno.readTextFile(path);
  await Deno.writeTextFile(path, updateRegister(doc));
  console.log(
    `${out}: ${file.length} bytes, ${MESSAGES.length} messages; docs/diagnostics.md updated`,
  );
}
